"""Illustrative multi-market universe. Figures are research fixtures, not live quotes."""

from __future__ import annotations

from quant.models import (
    ChainNode,
    Financials,
    IndustrySnapshot,
    Market,
    ResearchReport,
    SectorStyle,
    Stock,
    ValueChain,
)


def _f(**kwargs) -> Financials:
    return Financials(**kwargs)


STOCKS: dict[str, Stock] = {
    "600519.SS": Stock(
        symbol="600519.SS",
        name="贵州茅台",
        name_en="Kweichow Moutai",
        market=Market.A_SHARE,
        board="SSE",
        sector="主要消费",
        industry="白酒",
        style=SectorStyle.CONSUMER,
        currency="CNY",
        price=1480.0,
        shares_out=1.256e9,
        pe_ttm=22.5,
        pb=8.4,
        ev_ebitda=16.0,
        fcf_yield=0.041,
        dividend_yield=0.018,
        beta=0.72,
        southbound_eligible=False,
        northbound_eligible=True,
        dual_class=False,
        shenwan_industry="白酒",
        gics_industry="Distillers & Vintners",
        financials=_f(
            revenue=1.74e11,
            net_income=8.6e10,
            operating_cash_flow=8.1e10,
            free_cash_flow=7.6e10,
            total_equity=2.2e11,
            total_debt=5e9,
            cash=1.5e11,
            ebit=1.15e11,
            ebitda=1.18e11,
            interest_expense=2e8,
            current_assets=2.1e11,
            current_liabilities=4.5e10,
            revenue_cagr_3y=0.16,
            eps_cagr_3y=0.15,
            roe=0.31,
            roic=0.29,
            gross_margin=0.92,
            net_margin=0.49,
            earnings_volatility=0.08,
            receivable_days=2,
            inventory_days=1100,
        ),
        notes="北向核心持仓；品牌护城河极强，估值贵是常态。",
    ),
    "300750.SZ": Stock(
        symbol="300750.SZ",
        name="宁德时代",
        name_en="CATL",
        market=Market.A_SHARE,
        board="SZSE",
        sector="制造",
        industry="电池",
        style=SectorStyle.INDUSTRIAL,
        currency="CNY",
        price=210.0,
        shares_out=4.4e9,
        pe_ttm=19.8,
        pb=4.1,
        ev_ebitda=12.5,
        fcf_yield=0.028,
        dividend_yield=0.012,
        beta=1.25,
        southbound_eligible=False,
        northbound_eligible=True,
        dual_class=False,
        shenwan_industry="电池",
        gics_industry="Electrical Equipment",
        ah_pair_symbol="3750.HK",
        financials=_f(
            revenue=3.6e11,
            net_income=4.9e10,
            operating_cash_flow=7.2e10,
            free_cash_flow=2.6e10,
            total_equity=2.3e11,
            total_debt=1.1e11,
            cash=1.6e11,
            ebit=6.1e10,
            ebitda=8.8e10,
            interest_expense=3.2e9,
            current_assets=4.2e11,
            current_liabilities=2.4e11,
            revenue_cagr_3y=0.21,
            eps_cagr_3y=0.12,
            roe=0.22,
            roic=0.14,
            gross_margin=0.24,
            net_margin=0.136,
            earnings_volatility=0.22,
            receivable_days=70,
            inventory_days=85,
        ),
        notes="锂电周期+全球份额；A/H 价差是港股通研究的经典样本。",
    ),
    "3750.HK": Stock(
        symbol="3750.HK",
        name="宁德时代-H",
        name_en="CATL-H",
        market=Market.HK,
        board="HKEX",
        sector="制造",
        industry="电池",
        style=SectorStyle.INDUSTRIAL,
        currency="HKD",
        price=194.0,
        shares_out=4.4e8,
        pe_ttm=16.2,
        pb=3.3,
        ev_ebitda=10.4,
        fcf_yield=0.034,
        dividend_yield=0.014,
        beta=1.28,
        southbound_eligible=True,
        northbound_eligible=False,
        dual_class=False,
        shenwan_industry="电池",
        gics_industry="Electrical Equipment",
        ah_pair_symbol="300750.SZ",
        financials=_f(
            revenue=3.6e11,
            net_income=4.9e10,
            operating_cash_flow=7.2e10,
            free_cash_flow=2.6e10,
            total_equity=2.3e11,
            total_debt=1.1e11,
            cash=1.6e11,
            ebit=6.1e10,
            ebitda=8.8e10,
            interest_expense=3.2e9,
            current_assets=4.2e11,
            current_liabilities=2.4e11,
            revenue_cagr_3y=0.21,
            eps_cagr_3y=0.12,
            roe=0.22,
            roic=0.14,
            gross_margin=0.24,
            net_margin=0.136,
            earnings_volatility=0.22,
            receivable_days=70,
            inventory_days=85,
        ),
        notes="H 股样本价用于演示 A/H 溢价，不是实时盘口。",
    ),
    "600036.SS": Stock(
        symbol="600036.SS",
        name="招商银行",
        name_en="China Merchants Bank",
        market=Market.A_SHARE,
        board="SSE",
        sector="金融",
        industry="银行",
        style=SectorStyle.FINANCIAL,
        currency="CNY",
        price=36.5,
        shares_out=2.52e10,
        pe_ttm=6.4,
        pb=0.92,
        ev_ebitda=None,
        fcf_yield=None,
        dividend_yield=0.051,
        beta=0.88,
        southbound_eligible=False,
        northbound_eligible=True,
        dual_class=False,
        ah_pair_symbol="3968.HK",
        shenwan_industry="银行",
        gics_industry="Diversified Banks",
        financials=_f(
            revenue=3.3e11,
            net_income=1.46e11,
            operating_cash_flow=1.7e11,
            free_cash_flow=1.7e11,
            total_equity=1.05e12,
            total_debt=0.0,
            cash=0.0,
            ebit=1.46e11,
            ebitda=1.46e11,
            interest_expense=1.0,
            current_assets=1.0,
            current_liabilities=1.0,
            revenue_cagr_3y=0.04,
            eps_cagr_3y=0.05,
            roe=0.145,
            roic=0.12,
            gross_margin=0.0,
            net_margin=0.44,
            earnings_volatility=0.07,
            npl_ratio=0.0095,
            core_tier1=0.135,
        ),
        notes="零售银行质量标杆；A/H 长期溢价，适合讲折溢价而不是无风险套利。",
    ),
    "3968.HK": Stock(
        symbol="3968.HK",
        name="招商银行-H",
        name_en="CMB-H",
        market=Market.HK,
        board="HKEX",
        sector="金融",
        industry="银行",
        style=SectorStyle.FINANCIAL,
        currency="HKD",
        price=28.5,
        shares_out=4.59e9,
        pe_ttm=5.2,
        pb=0.74,
        ev_ebitda=None,
        fcf_yield=None,
        dividend_yield=0.062,
        beta=0.95,
        southbound_eligible=True,
        northbound_eligible=False,
        dual_class=False,
        ah_pair_symbol="600036.SS",
        shenwan_industry="银行",
        gics_industry="Diversified Banks",
        financials=_f(
            revenue=3.3e11,
            net_income=1.46e11,
            operating_cash_flow=1.7e11,
            free_cash_flow=1.7e11,
            total_equity=1.05e12,
            total_debt=0.0,
            cash=0.0,
            ebit=1.46e11,
            ebitda=1.46e11,
            interest_expense=1.0,
            current_assets=1.0,
            current_liabilities=1.0,
            revenue_cagr_3y=0.04,
            eps_cagr_3y=0.05,
            roe=0.145,
            roic=0.12,
            gross_margin=0.0,
            net_margin=0.44,
            earnings_volatility=0.07,
            npl_ratio=0.0095,
            core_tier1=0.135,
        ),
        notes="港股通南向重仓品种之一，股息和折价是常见叙事。",
    ),
    "00700.HK": Stock(
        symbol="00700.HK",
        name="腾讯控股",
        name_en="Tencent",
        market=Market.HK,
        board="HKEX",
        sector="可选消费/科技",
        industry="互联网平台",
        style=SectorStyle.INTERNET,
        currency="HKD",
        price=410.0,
        shares_out=9.3e9,
        pe_ttm=19.5,
        pb=3.6,
        ev_ebitda=13.2,
        fcf_yield=0.046,
        dividend_yield=0.011,
        beta=1.15,
        southbound_eligible=True,
        northbound_eligible=False,
        dual_class=True,
        gics_industry="Interactive Media & Services",
        financials=_f(
            revenue=6.6e11,
            net_income=1.9e11,
            operating_cash_flow=2.4e11,
            free_cash_flow=1.75e11,
            total_equity=9.5e11,
            total_debt=3.6e11,
            cash=4.1e11,
            ebit=1.85e11,
            ebitda=2.3e11,
            interest_expense=1.1e10,
            current_assets=5.2e11,
            current_liabilities=3.1e11,
            revenue_cagr_3y=0.09,
            eps_cagr_3y=0.11,
            roe=0.20,
            roic=0.13,
            gross_margin=0.51,
            net_margin=0.29,
            earnings_volatility=0.18,
            shares_dilution_3y=0.01,
            receivable_days=35,
        ),
        notes="港股通核心资产；游戏+广告+金融科技，监管与竞争是主风险。",
    ),
    "03690.HK": Stock(
        symbol="03690.HK",
        name="美团",
        name_en="Meituan",
        market=Market.HK,
        board="HKEX",
        sector="可选消费",
        industry="本地生活",
        style=SectorStyle.INTERNET,
        currency="HKD",
        price=125.0,
        shares_out=6.2e9,
        pe_ttm=24.0,
        pb=3.9,
        ev_ebitda=16.5,
        fcf_yield=0.032,
        dividend_yield=0.0,
        beta=1.42,
        southbound_eligible=True,
        northbound_eligible=False,
        dual_class=True,
        gics_industry="Internet & Direct Marketing Retail",
        financials=_f(
            revenue=3.3e11,
            net_income=2.7e10,
            operating_cash_flow=4.8e10,
            free_cash_flow=3.9e10,
            total_equity=1.7e11,
            total_debt=5.5e10,
            cash=1.4e11,
            ebit=3.4e10,
            ebitda=4.6e10,
            interest_expense=2.1e9,
            current_assets=1.9e11,
            current_liabilities=9.5e10,
            revenue_cagr_3y=0.18,
            eps_cagr_3y=0.25,
            roe=0.16,
            roic=0.11,
            gross_margin=0.35,
            net_margin=0.082,
            earnings_volatility=0.35,
            shares_dilution_3y=0.03,
            receivable_days=18,
        ),
        notes="本地生活竞争激烈，利润率对补贴和监管敏感。",
    ),
    "AAPL": Stock(
        symbol="AAPL",
        name="苹果",
        name_en="Apple",
        market=Market.US,
        board="NASDAQ",
        sector="信息技术",
        industry="消费电子",
        style=SectorStyle.TECH_HARDWARE,
        currency="USD",
        price=225.0,
        shares_out=1.52e10,
        pe_ttm=33.0,
        pb=48.0,
        ev_ebitda=24.0,
        fcf_yield=0.031,
        dividend_yield=0.0045,
        beta=1.18,
        southbound_eligible=False,
        northbound_eligible=False,
        dual_class=False,
        gics_industry="Technology Hardware",
        financials=_f(
            revenue=3.91e11,
            net_income=9.4e10,
            operating_cash_flow=1.18e11,
            free_cash_flow=1.08e11,
            total_equity=5.7e10,
            total_debt=1.06e11,
            cash=6.2e10,
            ebit=1.23e11,
            ebitda=1.34e11,
            interest_expense=3.9e9,
            current_assets=1.43e11,
            current_liabilities=1.65e11,
            revenue_cagr_3y=0.02,
            eps_cagr_3y=0.07,
            roe=1.45,
            roic=0.48,
            gross_margin=0.46,
            net_margin=0.24,
            earnings_volatility=0.11,
            shares_dilution_3y=-0.08,
            receivable_days=28,
            inventory_days=12,
        ),
        notes="美股质量+回购机器；PE 贵但 FCF 和资本回报极强。",
    ),
    "NVDA": Stock(
        symbol="NVDA",
        name="英伟达",
        name_en="NVIDIA",
        market=Market.US,
        board="NASDAQ",
        sector="信息技术",
        industry="半导体",
        style=SectorStyle.TECH_HARDWARE,
        currency="USD",
        price=120.0,
        shares_out=2.45e10,
        pe_ttm=42.0,
        pb=32.0,
        ev_ebitda=34.0,
        fcf_yield=0.019,
        dividend_yield=0.0003,
        beta=1.72,
        southbound_eligible=False,
        northbound_eligible=False,
        dual_class=False,
        gics_industry="Semiconductors",
        financials=_f(
            revenue=1.13e11,
            net_income=5.9e10,
            operating_cash_flow=6.4e10,
            free_cash_flow=5.7e10,
            total_equity=7.9e10,
            total_debt=1.0e10,
            cash=3.5e10,
            ebit=6.8e10,
            ebitda=7.1e10,
            interest_expense=2.6e8,
            current_assets=7.4e10,
            current_liabilities=1.8e10,
            revenue_cagr_3y=0.72,
            eps_cagr_3y=0.95,
            roe=0.91,
            roic=0.75,
            gross_margin=0.73,
            net_margin=0.52,
            earnings_volatility=0.40,
            receivable_days=45,
            inventory_days=110,
        ),
        notes="算力周期龙头；高增长对高估值，颠覆风险来自客户自制与资本开支回落。",
    ),
    "JPM": Stock(
        symbol="JPM",
        name="摩根大通",
        name_en="JPMorgan Chase",
        market=Market.US,
        board="NYSE",
        sector="金融",
        industry="银行",
        style=SectorStyle.FINANCIAL,
        currency="USD",
        price=210.0,
        shares_out=2.84e9,
        pe_ttm=12.2,
        pb=1.85,
        ev_ebitda=None,
        fcf_yield=None,
        dividend_yield=0.023,
        beta=1.08,
        southbound_eligible=False,
        northbound_eligible=False,
        dual_class=False,
        gics_industry="Diversified Banks",
        financials=_f(
            revenue=1.78e11,
            net_income=5.4e10,
            operating_cash_flow=6.1e10,
            free_cash_flow=6.1e10,
            total_equity=3.4e11,
            total_debt=0.0,
            cash=0.0,
            ebit=5.4e10,
            ebitda=5.4e10,
            interest_expense=1.0,
            current_assets=1.0,
            current_liabilities=1.0,
            revenue_cagr_3y=0.11,
            eps_cagr_3y=0.09,
            roe=0.16,
            roic=0.14,
            gross_margin=0.0,
            net_margin=0.30,
            earnings_volatility=0.16,
            npl_ratio=0.007,
            core_tier1=0.151,
        ),
        notes="美股银行对照样本：同样银行，美股 PB 体系与 A/H 完全不同。",
    ),
    "TSM": Stock(
        symbol="TSM",
        name="台积电",
        name_en="TSMC",
        market=Market.US,
        board="NYSE",
        sector="信息技术",
        industry="晶圆代工",
        style=SectorStyle.TECH_HARDWARE,
        currency="USD",
        price=175.0,
        shares_out=5.19e9,
        pe_ttm=28.0,
        pb=7.8,
        ev_ebitda=16.5,
        fcf_yield=0.022,
        dividend_yield=0.014,
        beta=1.22,
        southbound_eligible=False,
        northbound_eligible=False,
        dual_class=False,
        gics_industry="Semiconductors",
        financials=_f(
            revenue=9.0e10,
            net_income=3.5e10,
            operating_cash_flow=5.2e10,
            free_cash_flow=2.1e10,
            total_equity=1.6e11,
            total_debt=3.0e10,
            cash=6.5e10,
            ebit=4.2e10,
            ebitda=6.4e10,
            interest_expense=1.1e9,
            current_assets=8.0e10,
            current_liabilities=3.2e10,
            revenue_cagr_3y=0.18,
            eps_cagr_3y=0.16,
            roe=0.28,
            roic=0.22,
            gross_margin=0.54,
            net_margin=0.39,
            earnings_volatility=0.18,
            receivable_days=40,
            inventory_days=70,
        ),
        notes="先进制程瓶颈；AI 芯片最终都要经过代工产能。",
    ),
    "AVGO": Stock(
        symbol="AVGO",
        name="博通",
        name_en="Broadcom",
        market=Market.US,
        board="NASDAQ",
        sector="信息技术",
        industry="半导体",
        style=SectorStyle.TECH_HARDWARE,
        currency="USD",
        price=185.0,
        shares_out=4.7e9,
        pe_ttm=36.0,
        pb=18.0,
        ev_ebitda=28.0,
        fcf_yield=0.027,
        dividend_yield=0.012,
        beta=1.28,
        southbound_eligible=False,
        northbound_eligible=False,
        dual_class=False,
        gics_industry="Semiconductors",
        financials=_f(
            revenue=5.2e10,
            net_income=1.4e10,
            operating_cash_flow=2.0e10,
            free_cash_flow=1.8e10,
            total_equity=7.0e10,
            total_debt=7.4e10,
            cash=1.2e10,
            ebit=2.1e10,
            ebitda=2.8e10,
            interest_expense=2.2e9,
            current_assets=2.8e10,
            current_liabilities=2.0e10,
            revenue_cagr_3y=0.21,
            eps_cagr_3y=0.19,
            roe=0.24,
            roic=0.16,
            gross_margin=0.74,
            net_margin=0.27,
            earnings_volatility=0.16,
            receivable_days=50,
            inventory_days=80,
        ),
        notes="网络与定制 ASIC 吃到 AI 集群扩建；客户集中度高。",
    ),
    "MSFT": Stock(
        symbol="MSFT",
        name="微软",
        name_en="Microsoft",
        market=Market.US,
        board="NASDAQ",
        sector="信息技术",
        industry="云计算",
        style=SectorStyle.INTERNET,
        currency="USD",
        price=420.0,
        shares_out=7.43e9,
        pe_ttm=34.0,
        pb=11.5,
        ev_ebitda=22.0,
        fcf_yield=0.024,
        dividend_yield=0.007,
        beta=0.92,
        southbound_eligible=False,
        northbound_eligible=False,
        dual_class=False,
        gics_industry="Systems Software",
        financials=_f(
            revenue=2.45e11,
            net_income=8.8e10,
            operating_cash_flow=1.18e11,
            free_cash_flow=7.4e10,
            total_equity=2.7e11,
            total_debt=6.0e10,
            cash=7.5e10,
            ebit=1.1e11,
            ebitda=1.28e11,
            interest_expense=2.7e9,
            current_assets=1.6e11,
            current_liabilities=1.2e11,
            revenue_cagr_3y=0.13,
            eps_cagr_3y=0.14,
            roe=0.35,
            roic=0.22,
            gross_margin=0.69,
            net_margin=0.36,
            earnings_volatility=0.09,
            receivable_days=70,
            inventory_days=5,
        ),
        notes="云把 GPU 租给应用层；资本开支上升会压近两年 FCF。",
    ),
    "09988.HK": Stock(
        symbol="09988.HK",
        name="阿里巴巴",
        name_en="Alibaba",
        market=Market.HK,
        board="HKEX",
        sector="可选消费/科技",
        industry="互联网平台",
        style=SectorStyle.INTERNET,
        currency="HKD",
        price=92.0,
        shares_out=1.9e10,
        pe_ttm=14.5,
        pb=1.6,
        ev_ebitda=8.5,
        fcf_yield=0.055,
        dividend_yield=0.012,
        beta=1.20,
        southbound_eligible=True,
        northbound_eligible=False,
        dual_class=True,
        gics_industry="Broadline Retail",
        financials=_f(
            revenue=9.4e11,
            net_income=8.0e10,
            operating_cash_flow=1.5e11,
            free_cash_flow=1.1e11,
            total_equity=1.1e12,
            total_debt=2.2e11,
            cash=5.5e11,
            ebit=1.2e11,
            ebitda=1.7e11,
            interest_expense=8e9,
            current_assets=7.0e11,
            current_liabilities=4.2e11,
            revenue_cagr_3y=0.04,
            eps_cagr_3y=0.02,
            roe=0.08,
            roic=0.07,
            gross_margin=0.37,
            net_margin=0.09,
            earnings_volatility=0.22,
            receivable_days=18,
            inventory_days=25,
        ),
        notes="云与电商平台同时出现在 AI 中游；利润仍看国内消费与云份额。",
    ),
    "002594.SZ": Stock(
        symbol="002594.SZ",
        name="比亚迪",
        name_en="BYD",
        market=Market.A_SHARE,
        board="SZSE",
        sector="制造",
        industry="新能源车",
        style=SectorStyle.INDUSTRIAL,
        currency="CNY",
        price=280.0,
        shares_out=2.9e9,
        pe_ttm=22.0,
        pb=4.6,
        ev_ebitda=14.0,
        fcf_yield=0.015,
        dividend_yield=0.011,
        beta=1.35,
        southbound_eligible=False,
        northbound_eligible=True,
        dual_class=False,
        ah_pair_symbol="01211.HK",
        shenwan_industry="汽车",
        gics_industry="Automobile Manufacturers",
        financials=_f(
            revenue=7.0e11,
            net_income=3.1e10,
            operating_cash_flow=8.5e10,
            free_cash_flow=2.2e10,
            total_equity=1.8e11,
            total_debt=1.4e11,
            cash=1.1e11,
            ebit=4.0e10,
            ebitda=7.5e10,
            interest_expense=4e9,
            current_assets=3.6e11,
            current_liabilities=3.1e11,
            revenue_cagr_3y=0.38,
            eps_cagr_3y=0.42,
            roe=0.19,
            roic=0.11,
            gross_margin=0.20,
            net_margin=0.044,
            earnings_volatility=0.28,
            receivable_days=25,
            inventory_days=70,
        ),
        notes="整车吃电池成本；价格战会把上游利润池继续往下游挤。",
    ),
    "01211.HK": Stock(
        symbol="01211.HK",
        name="比亚迪股份",
        name_en="BYD-H",
        market=Market.HK,
        board="HKEX",
        sector="制造",
        industry="新能源车",
        style=SectorStyle.INDUSTRIAL,
        currency="HKD",
        price=280.0,
        shares_out=1.1e9,
        pe_ttm=18.5,
        pb=3.8,
        ev_ebitda=11.5,
        fcf_yield=0.021,
        dividend_yield=0.014,
        beta=1.40,
        southbound_eligible=True,
        northbound_eligible=False,
        dual_class=False,
        ah_pair_symbol="002594.SZ",
        gics_industry="Automobile Manufacturers",
        financials=_f(
            revenue=7.0e11,
            net_income=3.1e10,
            operating_cash_flow=8.5e10,
            free_cash_flow=2.2e10,
            total_equity=1.8e11,
            total_debt=1.4e11,
            cash=1.1e11,
            ebit=4.0e10,
            ebitda=7.5e10,
            interest_expense=4e9,
            current_assets=3.6e11,
            current_liabilities=3.1e11,
            revenue_cagr_3y=0.38,
            eps_cagr_3y=0.42,
            roe=0.19,
            roic=0.11,
            gross_margin=0.20,
            net_margin=0.044,
            earnings_volatility=0.28,
            receivable_days=25,
            inventory_days=70,
        ),
        notes="与 A 股同一集团，港股通可买；价差反映两地投资者结构。",
    ),
}


INDUSTRIES: dict[str, IndustrySnapshot] = {
    "白酒": IndustrySnapshot(
        name="白酒",
        name_en="Baijiu",
        markets=(Market.A_SHARE,),
        growth_3y=0.08,
        expected_growth_2y=0.05,
        cr5=0.62,
        hhi=1450,
        median_roe=0.22,
        median_roic=0.20,
        policy_score=58,
        disruption_risk=25,
        valuation_percentile=62,
        profit_pool_trend=0.01,
        cycle_position="mid",
        leaders=("600519.SS",),
        aliases=("白酒", "Baijiu", "高端白酒"),
        constituents=("600519.SS",),
        notes="高端宴席与礼品需求稳，大众价格带竞争更卷；几乎是纯 A 股行业。",
    ),
    "动力电池": IndustrySnapshot(
        name="动力电池",
        name_en="EV Battery",
        markets=(Market.A_SHARE, Market.HK),
        growth_3y=0.24,
        expected_growth_2y=0.12,
        cr5=0.71,
        hhi=1800,
        median_roe=0.14,
        median_roic=0.10,
        policy_score=72,
        disruption_risk=55,
        valuation_percentile=48,
        profit_pool_trend=-0.02,
        cycle_position="mid",
        leaders=("300750.SZ", "3750.HK"),
        aliases=("电池", "EV Battery", "锂电"),
        constituents=("300750.SZ", "3750.HK"),
        notes="全球份额向龙头集中，但资本开支与价格战会吃掉利润池。",
    ),
    "新能源车": IndustrySnapshot(
        name="新能源车",
        name_en="NEV",
        markets=(Market.A_SHARE, Market.HK),
        growth_3y=0.32,
        expected_growth_2y=0.14,
        cr5=0.45,
        hhi=980,
        median_roe=0.12,
        median_roic=0.08,
        policy_score=70,
        disruption_risk=62,
        valuation_percentile=55,
        profit_pool_trend=-0.03,
        cycle_position="mid",
        leaders=("002594.SZ", "01211.HK"),
        aliases=("汽车", "电动车", "NEV", "EV"),
        constituents=("002594.SZ", "01211.HK"),
        notes="量还在长，价在打；利润常被补贴退坡和价格战从整车层挤走。",
    ),
    "中资银行": IndustrySnapshot(
        name="中资银行",
        name_en="Chinese Banks",
        markets=(Market.A_SHARE, Market.HK),
        growth_3y=0.03,
        expected_growth_2y=0.03,
        cr5=0.48,
        hhi=900,
        median_roe=0.10,
        median_roic=0.09,
        policy_score=52,
        disruption_risk=35,
        valuation_percentile=22,
        profit_pool_trend=-0.01,
        cycle_position="trough",
        leaders=("600036.SS", "3968.HK"),
        aliases=("银行", "Chinese Banks"),
        constituents=("600036.SS", "3968.HK"),
        notes="资产质量与净息差是主线；A 股溢价、H 股折价长期存在。",
    ),
    "美股银行": IndustrySnapshot(
        name="美股银行",
        name_en="US Banks",
        markets=(Market.US,),
        growth_3y=0.09,
        expected_growth_2y=0.06,
        cr5=0.42,
        hhi=850,
        median_roe=0.15,
        median_roic=0.13,
        policy_score=60,
        disruption_risk=40,
        valuation_percentile=58,
        profit_pool_trend=0.02,
        cycle_position="mid",
        leaders=("JPM",),
        aliases=("US Banks", "美国银行"),
        constituents=("JPM",),
        notes="同一银行生意，美股用另一套 PB 与利率周期，不能和中资银行横比倍数。",
    ),
    "互联网平台": IndustrySnapshot(
        name="互联网平台",
        name_en="China Internet",
        markets=(Market.HK, Market.US),
        growth_3y=0.07,
        expected_growth_2y=0.08,
        cr5=0.68,
        hhi=1600,
        median_roe=0.13,
        median_roic=0.10,
        policy_score=48,
        disruption_risk=60,
        valuation_percentile=40,
        profit_pool_trend=0.03,
        cycle_position="early",
        leaders=("00700.HK", "09988.HK"),
        aliases=("中国互联网", "China Internet"),
        constituents=("00700.HK", "09988.HK"),
        notes="监管从收缩走向常态化，但竞争与广告预算仍决定利润弹性。",
    ),
    "本地生活": IndustrySnapshot(
        name="本地生活",
        name_en="Local Services",
        markets=(Market.HK,),
        growth_3y=0.11,
        expected_growth_2y=0.09,
        cr5=0.58,
        hhi=1250,
        median_roe=0.08,
        median_roic=0.06,
        policy_score=50,
        disruption_risk=58,
        valuation_percentile=46,
        profit_pool_trend=0.02,
        cycle_position="early",
        leaders=("03690.HK",),
        aliases=("到店", "外卖", "Local Services"),
        constituents=("03690.HK",),
        notes="交易额可以很大，利润取决于补贴强度；AI 目前更多是成本项。",
    ),
    "全球半导体": IndustrySnapshot(
        name="全球半导体",
        name_en="Global Semiconductors",
        markets=(Market.US, Market.HK, Market.A_SHARE),
        growth_3y=0.18,
        expected_growth_2y=0.14,
        cr5=0.55,
        hhi=1300,
        median_roe=0.18,
        median_roic=0.16,
        policy_score=44,
        disruption_risk=70,
        valuation_percentile=78,
        profit_pool_trend=0.08,
        cycle_position="mid",
        leaders=("NVDA", "AVGO"),
        aliases=("半导体", "GPU", "AI芯片", "算力芯片"),
        constituents=("NVDA", "AVGO"),
        notes="AI 资本开支驱动；出口管制与客户自制是美股/A 股共同变量。",
    ),
    "晶圆代工": IndustrySnapshot(
        name="晶圆代工",
        name_en="Foundry",
        markets=(Market.US,),
        growth_3y=0.16,
        expected_growth_2y=0.12,
        cr5=0.72,
        hhi=2100,
        median_roe=0.24,
        median_roic=0.18,
        policy_score=46,
        disruption_risk=50,
        valuation_percentile=72,
        profit_pool_trend=0.05,
        cycle_position="mid",
        leaders=("TSM",),
        aliases=("代工", "Foundry", "先进制程"),
        constituents=("TSM",),
        notes="先进制程产能是物理瓶颈；设计公司再强也要排队。",
    ),
    "云计算": IndustrySnapshot(
        name="云计算",
        name_en="Cloud",
        markets=(Market.US, Market.HK),
        growth_3y=0.17,
        expected_growth_2y=0.13,
        cr5=0.66,
        hhi=1700,
        median_roe=0.22,
        median_roic=0.14,
        policy_score=55,
        disruption_risk=52,
        valuation_percentile=74,
        profit_pool_trend=0.04,
        cycle_position="mid",
        leaders=("MSFT", "09988.HK"),
        aliases=("云", "Cloud", "IaaS"),
        constituents=("MSFT", "09988.HK"),
        notes="把上游算力转租给应用；利润看定价权，风险看资本开支回落。",
    ),
    "消费电子": IndustrySnapshot(
        name="消费电子",
        name_en="Consumer Electronics",
        markets=(Market.US,),
        growth_3y=0.03,
        expected_growth_2y=0.05,
        cr5=0.60,
        hhi=1400,
        median_roe=0.40,
        median_roic=0.30,
        policy_score=62,
        disruption_risk=48,
        valuation_percentile=80,
        profit_pool_trend=0.01,
        cycle_position="late",
        leaders=("AAPL",),
        aliases=("手机", "消费硬件", "Consumer Electronics"),
        constituents=("AAPL",),
        notes="硬件入口和回购机器；端侧 AI 是叙事，利润仍主要来自生态和价位。",
    ),
}


CHAINS: dict[str, ValueChain] = {
    "ai": ValueChain(
        id="ai",
        name="人工智能产业链",
        name_en="AI value chain",
        aliases=("AI", "ai", "人工智能", "算力", "大模型", "算力产业链", "AI上下游"),
        thesis="利润最先停在不可替代的算力和先进制程；云分成租用；应用层多数是费用项。",
        notes="样本地图，不是完整产业普查。出口管制、客户自制和资本开支回落会改瓶颈位置。",
        nodes=(
            ChainNode(
                role="upstream",
                industry="全球半导体",
                captures="训练/推理芯片：量价弹性最大，也是出口管制焦点。",
                bottleneck=True,
            ),
            ChainNode(
                role="upstream",
                industry="晶圆代工",
                captures="先进制程产能：没有它，上游设计订单无法变成货。",
                bottleneck=True,
            ),
            ChainNode(
                role="midstream",
                industry="云计算",
                captures="把 GPU 时数租给模型公司，赚差价也承担折旧。",
            ),
            ChainNode(
                role="midstream",
                industry="互联网平台",
                captures="中文应用分发、广告和云；AI 能提效，但不自动变成和 GPU 一样的利润池。",
            ),
            ChainNode(
                role="downstream",
                industry="消费电子",
                captures="端侧入口。硬件周期弱于算力，AI 功能更多是保住 ASP。",
            ),
            ChainNode(
                role="downstream",
                industry="本地生活",
                captures="应用层：订单很大，AI 目前主要降成本，不是单独卖算力。",
            ),
        ),
    ),
    "ev": ValueChain(
        id="ev",
        name="新能源车产业链",
        name_en="EV value chain",
        aliases=("新能源", "电动车产业链", "锂电池产业链", "EV chain"),
        thesis="装车量可以很好看，利润却经常停在电池龙头而不是所有整车厂。",
        notes="价格战会把利润从下游整车挤回有成本曲线的电池层，也可能两头一起打薄。",
        nodes=(
            ChainNode(
                role="upstream",
                industry="动力电池",
                captures="电芯与系统：技术路线和产能利用率决定利润。",
                bottleneck=True,
            ),
            ChainNode(
                role="downstream",
                industry="新能源车",
                captures="整车：量的入口，价的战场。",
            ),
        ),
    ),
    "banks": ValueChain(
        id="banks",
        name="中美银行对照",
        name_en="Banking comparison",
        aliases=("银行对照", "中美银行"),
        thesis="这不是上下游，是同一商业模式在两套利率、监管和估值尺子下的对照。",
        notes="不要把招行 PB 和摩根大通 PB 直接相减当成便宜。",
        nodes=(
            ChainNode(role="midstream", industry="中资银行", captures="净息差、资产质量、A/H 投资者结构。"),
            ChainNode(role="midstream", industry="美股银行", captures="美债利率、资本回报、美元流动性。"),
        ),
    ),
}


REPORTS: dict[str, ResearchReport] = {
    "tencent-init": ResearchReport(
        title="腾讯：游戏与广告修复，首次覆盖买入",
        broker="某券商海外",
        language="zh",
        symbol="00700.HK",
        rating="buy",
        target_price=620.0,
        current_price=410.0,
        published="2026-03-01",
        has_initiation=True,
        broker_is_underwriter=False,
        has_quant_model=False,
        body=(
            "核心结论：我们认为腾讯将重新获得游戏与广告的利润弹性。"
            "投资逻辑是国内游戏版号常态化，广告主预算回升，以及金融科技合规后利润率修复。"
            "关键假设包括：明年游戏收入增长 12%，广告 ASP 提升 6%，市占维持。"
            "目标价 620 港元，对应 28x PE，未做完整敏感性分析。"
            "风险：宏观经济波动，监管再收紧，竞争加剧。"
            "渠道调研显示部分广告主预算回升，但样本有限。"
        ),
    ),
    "cmb-ah": ResearchReport(
        title="招商银行 A/H：质量溢价仍在，H 股股息更有吸引力",
        broker="中资研究所",
        language="zh",
        symbol="3968.HK",
        rating="overweight",
        target_price=46.0,
        current_price=28.5,
        published="2026-02-12",
        has_quant_model=True,
        body=(
            "核心结论：招行零售资产质量仍优于同业，H 股 PB 0.74x 低于 A 股。"
            "投资逻辑：净息差企稳、财富管理中收回升、港股通南向持续增持。"
            "关键假设：NPL 维持 1% 以下，ROE 14%-15%，派息率 35%。"
            "估值采用 PB-ROE 与 DDM，并对净息差做了敏感性。"
            "风险：房地产相关敞口恶化、零售信贷成本上升、若内地资金流出则折价扩大。"
            "公告显示核心一级资本充足率 13.5%。"
        ),
    ),
    "nvda-hype": ResearchReport(
        title="NVIDIA: only way is up",
        broker="Promo Capital",
        language="en",
        symbol="NVDA",
        rating="buy",
        target_price=260.0,
        current_price=120.0,
        published="2026-01-08",
        has_initiation=True,
        broker_is_underwriter=True,
        body=(
            "We believe NVIDIA will keep winning forever. Space is huge and certain. "
            "No real bear case. Must go up. Target implies 2x from here. "
            "Macro risk only. We are also the underwriter on a related financing."
        ),
    ),
}


CONNECT_FLOWS = {
    "00700.HK": {"southbound_holding_change_20d": 0.018, "southbound_rank": 1},
    "03690.HK": {"southbound_holding_change_20d": -0.006, "southbound_rank": 8},
    "3968.HK": {"southbound_holding_change_20d": 0.011, "southbound_rank": 5},
    "3750.HK": {"southbound_holding_change_20d": 0.004, "southbound_rank": 16},
    "01211.HK": {"southbound_holding_change_20d": 0.009, "southbound_rank": 12},
    "09988.HK": {"southbound_holding_change_20d": 0.005, "southbound_rank": 6},
    "600519.SS": {"northbound_holding_change_20d": 0.007, "northbound_rank": 3},
    "300750.SZ": {"northbound_holding_change_20d": -0.009, "northbound_rank": 11},
    "600036.SS": {"northbound_holding_change_20d": 0.003, "northbound_rank": 9},
    "002594.SZ": {"northbound_holding_change_20d": 0.006, "northbound_rank": 14},
}


def universe() -> list[Stock]:
    return list(STOCKS.values())


def get_stock(symbol: str) -> Stock:
    key = symbol.strip()
    if key in STOCKS:
        return STOCKS[key]
    upper = {k.upper(): k for k in STOCKS}
    if key.upper() in upper:
        return STOCKS[upper[key.upper()]]
    raise KeyError(f"unknown sample symbol: {symbol}")


def industries() -> list[IndustrySnapshot]:
    return list(INDUSTRIES.values())


def _norm(text: str) -> str:
    return text.strip().lower().replace(" ", "").replace("-", "").replace("_", "")


def get_industry(name: str) -> IndustrySnapshot:
    key = name.strip()
    if key in INDUSTRIES:
        return INDUSTRIES[key]
    needle = _norm(key)
    for item in INDUSTRIES.values():
        labels = (item.name, item.name_en, *item.aliases)
        if needle in {_norm(label) for label in labels}:
            return item
    raise KeyError(f"unknown industry: {name}")


def chains() -> list[ValueChain]:
    return list(CHAINS.values())


def get_chain(name: str) -> ValueChain:
    key = name.strip()
    if key in CHAINS:
        return CHAINS[key]
    needle = _norm(key)
    for chain in CHAINS.values():
        labels = (chain.id, chain.name, chain.name_en, *chain.aliases)
        if needle in {_norm(label) for label in labels}:
            return chain
    raise KeyError(f"unknown chain: {name}")


def industry_constituents(industry: IndustrySnapshot) -> list[Stock]:
    symbols = industry.constituents or industry.leaders
    out: list[Stock] = []
    seen: set[str] = set()
    for symbol in symbols:
        if symbol in seen:
            continue
        seen.add(symbol)
        try:
            out.append(get_stock(symbol))
        except KeyError:
            continue
    return out
