"""Additional sample names, industries, chains, and IPO pipeline."""

from __future__ import annotations

from dataclasses import replace

from quant.models import (
    ChainNode,
    Financials,
    IndustrySnapshot,
    IPODeal,
    Market,
    SectorStyle,
    Stock,
    ValueChain,
)


def _f(**kwargs) -> Financials:
    return Financials(**kwargs)


def _corp(**kw) -> Financials:
    base = dict(
        revenue=1.2e11,
        net_income=1.8e10,
        operating_cash_flow=2.4e10,
        free_cash_flow=1.5e10,
        total_equity=1.1e11,
        total_debt=4e10,
        cash=2.5e10,
        ebit=2.4e10,
        ebitda=3.0e10,
        interest_expense=1.2e9,
        current_assets=6e10,
        current_liabilities=3.5e10,
        revenue_cagr_3y=0.09,
        eps_cagr_3y=0.08,
        roe=0.16,
        roic=0.12,
        gross_margin=0.38,
        net_margin=0.15,
        earnings_volatility=0.16,
    )
    base.update(kw)
    return _f(**base)


def _fin(**kw) -> Financials:
    base = dict(
        revenue=2.8e11,
        net_income=1.1e11,
        operating_cash_flow=1.3e11,
        free_cash_flow=1.3e11,
        total_equity=9e11,
        total_debt=0.0,
        cash=0.0,
        ebit=1.1e11,
        ebitda=1.1e11,
        interest_expense=1.0,
        current_assets=1.0,
        current_liabilities=1.0,
        revenue_cagr_3y=0.04,
        eps_cagr_3y=0.05,
        roe=0.13,
        roic=0.11,
        gross_margin=0.0,
        net_margin=0.39,
        earnings_volatility=0.08,
        npl_ratio=None,
        core_tier1=None,
    )
    base.update(kw)
    return _f(**base)


def extra_stocks() -> dict[str, Stock]:
    rows = [
        Stock(
            symbol="000858.SZ",
            name="五粮液",
            name_en="Wuliangye",
            market=Market.A_SHARE,
            board="SZSE",
            sector="主要消费",
            industry="白酒",
            style=SectorStyle.CONSUMER,
            currency="CNY",
            price=128.0,
            shares_out=3.88e9,
            pe_ttm=16.5,
            pb=4.1,
            ev_ebitda=11.5,
            fcf_yield=0.048,
            dividend_yield=0.032,
            beta=0.86,
            southbound_eligible=False,
            northbound_eligible=True,
            dual_class=False,
            shenwan_industry="白酒",
            gics_industry="Distillers & Vintners",
            financials=_corp(
                revenue=8.5e10,
                net_income=3.1e10,
                roe=0.24,
                roic=0.22,
                gross_margin=0.75,
                net_margin=0.36,
                inventory_days=900,
            ),
            notes="次高端放量、高端稳；和茅台同切片但不能用同一 PE 叙事。",
        ),
        Stock(
            symbol="601318.SS",
            name="中国平安",
            name_en="Ping An",
            market=Market.A_SHARE,
            board="SSE",
            sector="金融",
            industry="保险",
            style=SectorStyle.FINANCIAL,
            currency="CNY",
            price=48.0,
            shares_out=1.82e10,
            pe_ttm=8.5,
            pb=0.95,
            ev_ebitda=None,
            fcf_yield=None,
            dividend_yield=0.048,
            beta=1.05,
            southbound_eligible=False,
            northbound_eligible=True,
            dual_class=False,
            ah_pair_symbol="02318.HK",
            shenwan_industry="保险",
            gics_industry="Life & Health Insurance",
            financials=_fin(revenue=8e11, net_income=1.2e11, roe=0.15),
            notes="寿险 + 银行综合金融；NBV 和地产敞口是主线，不是简单银行 PB。",
        ),
        Stock(
            symbol="02318.HK",
            name="中国平安-H",
            name_en="Ping An-H",
            market=Market.HK,
            board="HKEX",
            sector="金融",
            industry="保险",
            style=SectorStyle.FINANCIAL,
            currency="HKD",
            price=42.0,
            shares_out=7.45e9,
            pe_ttm=7.2,
            pb=0.82,
            ev_ebitda=None,
            fcf_yield=None,
            dividend_yield=0.055,
            beta=1.12,
            southbound_eligible=True,
            northbound_eligible=False,
            dual_class=False,
            ah_pair_symbol="601318.SS",
            shenwan_industry="保险",
            gics_industry="Life & Health Insurance",
            financials=_fin(revenue=8e11, net_income=1.2e11, roe=0.15),
            notes="南向可买的保险对照；H 股折价常见，不是无风险套利。",
        ),
        Stock(
            symbol="01299.HK",
            name="友邦保险",
            name_en="AIA",
            market=Market.HK,
            board="HKEX",
            sector="金融",
            industry="保险",
            style=SectorStyle.FINANCIAL,
            currency="HKD",
            price=62.0,
            shares_out=1.13e10,
            pe_ttm=16.0,
            pb=2.1,
            ev_ebitda=None,
            fcf_yield=None,
            dividend_yield=0.028,
            beta=0.92,
            southbound_eligible=True,
            northbound_eligible=False,
            dual_class=False,
            shenwan_industry="保险",
            gics_industry="Life & Health Insurance",
            financials=_fin(revenue=3.2e11, net_income=6e10, roe=0.13),
            notes="亚洲代理人网络；和平安同业不同估值尺子（EV vs P/B）。",
        ),
        Stock(
            symbol="600276.SS",
            name="恒瑞医药",
            name_en="Hengrui Medicine",
            market=Market.A_SHARE,
            board="SSE",
            sector="医药",
            industry="创新药",
            style=SectorStyle.HEALTHCARE,
            currency="CNY",
            price=46.0,
            shares_out=6.4e9,
            pe_ttm=48.0,
            pb=6.5,
            ev_ebitda=32.0,
            fcf_yield=0.012,
            dividend_yield=0.008,
            beta=0.78,
            southbound_eligible=False,
            northbound_eligible=True,
            dual_class=False,
            shenwan_industry="化学制药",
            gics_industry="Pharmaceuticals",
            financials=_corp(
                revenue=2.7e10,
                net_income=6.3e9,
                roe=0.12,
                roic=0.10,
                gross_margin=0.84,
                net_margin=0.23,
                revenue_cagr_3y=0.06,
                eps_cagr_3y=0.04,
            ),
            notes="仿创结合；管线兑现比 PE 更重要，医保谈判是政策分。",
        ),
        Stock(
            symbol="06160.HK",
            name="百济神州",
            name_en="BeiGene",
            market=Market.HK,
            board="HKEX",
            sector="医药",
            industry="创新药",
            style=SectorStyle.HEALTHCARE,
            currency="HKD",
            price=138.0,
            shares_out=1.38e9,
            pe_ttm=None,
            pb=7.2,
            ev_ebitda=None,
            fcf_yield=None,
            dividend_yield=0.0,
            beta=1.15,
            southbound_eligible=True,
            northbound_eligible=False,
            dual_class=False,
            shenwan_industry="生物制品",
            gics_industry="Biotechnology",
            financials=_corp(
                revenue=2.5e10,
                net_income=-3e9,
                roe=-0.08,
                roic=-0.06,
                gross_margin=0.82,
                net_margin=-0.12,
                revenue_cagr_3y=0.35,
                eps_cagr_3y=0.0,
                earnings_volatility=0.4,
            ),
            notes="商业化爬坡、尚未稳定盈利；PE 无意义，应对管线和现金。",
        ),
        Stock(
            symbol="LLY",
            name="礼来",
            name_en="Eli Lilly",
            market=Market.US,
            board="NYSE",
            sector="医药",
            industry="创新药",
            style=SectorStyle.HEALTHCARE,
            currency="USD",
            price=780.0,
            shares_out=9.0e8,
            pe_ttm=62.0,
            pb=48.0,
            ev_ebitda=40.0,
            fcf_yield=0.011,
            dividend_yield=0.007,
            beta=0.42,
            southbound_eligible=False,
            northbound_eligible=False,
            dual_class=False,
            shenwan_industry="化学制药",
            gics_industry="Pharmaceuticals",
            financials=_corp(
                revenue=4.5e10,
                net_income=1.05e10,
                roe=0.55,
                roic=0.32,
                gross_margin=0.81,
                net_margin=0.23,
                revenue_cagr_3y=0.22,
                eps_cagr_3y=0.28,
            ),
            notes="减重与代谢管线定价权极强；估值贵，颠覆来自竞品和支付方。",
        ),
        Stock(
            symbol="601012.SS",
            name="隆基绿能",
            name_en="LONGi",
            market=Market.A_SHARE,
            board="SSE",
            sector="制造",
            industry="光伏",
            style=SectorStyle.ENERGY,
            currency="CNY",
            price=16.5,
            shares_out=7.6e9,
            pe_ttm=18.0,
            pb=1.6,
            ev_ebitda=9.0,
            fcf_yield=0.02,
            dividend_yield=0.015,
            beta=1.28,
            southbound_eligible=False,
            northbound_eligible=True,
            dual_class=False,
            shenwan_industry="光伏设备",
            gics_industry="Electrical Equipment",
            financials=_corp(
                revenue=8e10,
                net_income=8e9,
                roe=0.08,
                roic=0.06,
                gross_margin=0.18,
                net_margin=0.10,
                revenue_cagr_3y=0.12,
                eps_cagr_3y=-0.05,
                earnings_volatility=0.35,
            ),
            notes="硅片到组件周期股；产能与价格战决定利润池，不是装机量叙事。",
        ),
        Stock(
            symbol="601857.SS",
            name="中国石油",
            name_en="PetroChina",
            market=Market.A_SHARE,
            board="SSE",
            sector="能源",
            industry="石油",
            style=SectorStyle.ENERGY,
            currency="CNY",
            price=8.4,
            shares_out=1.83e11,
            pe_ttm=8.8,
            pb=0.92,
            ev_ebitda=4.5,
            fcf_yield=0.09,
            dividend_yield=0.055,
            beta=0.82,
            southbound_eligible=False,
            northbound_eligible=True,
            dual_class=False,
            shenwan_industry="石油开采",
            gics_industry="Integrated Oil & Gas",
            financials=_corp(
                revenue=3.0e12,
                net_income=1.6e11,
                roe=0.11,
                roic=0.08,
                gross_margin=0.22,
                net_margin=0.053,
                revenue_cagr_3y=0.03,
            ),
            notes="油价 + 分红；A 股流动性溢价，和美油巨头不能横比 PE。",
        ),
        Stock(
            symbol="00883.HK",
            name="中国海洋石油",
            name_en="CNOOC",
            market=Market.HK,
            board="HKEX",
            sector="能源",
            industry="石油",
            style=SectorStyle.ENERGY,
            currency="HKD",
            price=18.5,
            shares_out=4.75e10,
            pe_ttm=6.5,
            pb=1.15,
            ev_ebitda=3.2,
            fcf_yield=0.14,
            dividend_yield=0.07,
            beta=0.95,
            southbound_eligible=True,
            northbound_eligible=False,
            dual_class=False,
            shenwan_industry="石油开采",
            gics_industry="Oil & Gas Exploration",
            financials=_corp(
                revenue=4.2e11,
                net_income=1.2e11,
                roe=0.22,
                roic=0.18,
                gross_margin=0.48,
                net_margin=0.29,
                revenue_cagr_3y=0.08,
            ),
            notes="南向高股息能源；产量与布伦特是主线。",
        ),
        Stock(
            symbol="XOM",
            name="埃克森美孚",
            name_en="Exxon Mobil",
            market=Market.US,
            board="NYSE",
            sector="能源",
            industry="石油",
            style=SectorStyle.ENERGY,
            currency="USD",
            price=112.0,
            shares_out=4.4e9,
            pe_ttm=14.0,
            pb=1.9,
            ev_ebitda=7.5,
            fcf_yield=0.055,
            dividend_yield=0.033,
            beta=0.88,
            southbound_eligible=False,
            northbound_eligible=False,
            dual_class=False,
            shenwan_industry="石油开采",
            gics_industry="Integrated Oil & Gas",
            financials=_corp(
                revenue=3.3e11,
                net_income=3.3e10,
                roe=0.16,
                roic=0.12,
                gross_margin=0.24,
                net_margin=0.10,
                revenue_cagr_3y=0.06,
            ),
            notes="美股油气对照：回购 + 上游资本纪律，和中石油不是同一套分红政治。",
        ),
        Stock(
            symbol="600900.SS",
            name="长江电力",
            name_en="Yangtze Power",
            market=Market.A_SHARE,
            board="SSE",
            sector="公用事业",
            industry="公用事业",
            style=SectorStyle.UTILITY,
            currency="CNY",
            price=28.5,
            shares_out=2.45e10,
            pe_ttm=20.0,
            pb=3.1,
            ev_ebitda=12.0,
            fcf_yield=0.035,
            dividend_yield=0.034,
            beta=0.35,
            southbound_eligible=False,
            northbound_eligible=True,
            dual_class=False,
            shenwan_industry="水电",
            gics_industry="Electric Utilities",
            financials=_corp(
                revenue=8e10,
                net_income=3.2e10,
                roe=0.16,
                roic=0.10,
                gross_margin=0.62,
                net_margin=0.40,
                revenue_cagr_3y=0.07,
                earnings_volatility=0.08,
            ),
            notes="水电分红机器；来水与电价，不是成长股。",
        ),
        Stock(
            symbol="00388.HK",
            name="香港交易所",
            name_en="HKEX",
            market=Market.HK,
            board="HKEX",
            sector="金融",
            industry="交易所",
            style=SectorStyle.FINANCIAL,
            currency="HKD",
            price=310.0,
            shares_out=1.27e9,
            pe_ttm=28.0,
            pb=7.5,
            ev_ebitda=20.0,
            fcf_yield=0.03,
            dividend_yield=0.028,
            beta=1.05,
            southbound_eligible=True,
            northbound_eligible=False,
            dual_class=False,
            shenwan_industry="多元金融",
            gics_industry="Financial Exchanges & Data",
            financials=_corp(
                revenue=1.6e10,
                net_income=1.0e10,
                roe=0.26,
                roic=0.22,
                gross_margin=0.0,
                net_margin=0.62,
                revenue_cagr_3y=0.05,
            ),
            notes="成交额 + 新股 + 互联互通；本身就是 IPO 管道的收费站。",
        ),
        Stock(
            symbol="01810.HK",
            name="小米集团-W",
            name_en="Xiaomi",
            market=Market.HK,
            board="HKEX",
            sector="可选消费",
            industry="消费电子",
            style=SectorStyle.TECH_HARDWARE,
            currency="HKD",
            price=42.0,
            shares_out=2.5e10,
            pe_ttm=28.0,
            pb=4.0,
            ev_ebitda=18.0,
            fcf_yield=0.025,
            dividend_yield=0.0,
            beta=1.22,
            southbound_eligible=True,
            northbound_eligible=False,
            dual_class=True,
            shenwan_industry="消费电子",
            gics_industry="Consumer Electronics",
            financials=_corp(
                revenue=3.3e11,
                net_income=2.0e10,
                roe=0.18,
                roic=0.14,
                gross_margin=0.21,
                net_margin=0.06,
                revenue_cagr_3y=0.14,
            ),
            notes="手机 + 汽车叙事；和苹果同切片但利润池薄得多。WVR。",
        ),
        Stock(
            symbol="TSLA",
            name="特斯拉",
            name_en="Tesla",
            market=Market.US,
            board="NASDAQ",
            sector="可选消费",
            industry="新能源车",
            style=SectorStyle.INDUSTRIAL,
            currency="USD",
            price=248.0,
            shares_out=3.2e9,
            pe_ttm=72.0,
            pb=12.0,
            ev_ebitda=45.0,
            fcf_yield=0.008,
            dividend_yield=0.0,
            beta=1.85,
            southbound_eligible=False,
            northbound_eligible=False,
            dual_class=False,
            shenwan_industry="乘用车",
            gics_industry="Automobile Manufacturers",
            financials=_corp(
                revenue=9.7e10,
                net_income=7e9,
                roe=0.15,
                roic=0.10,
                gross_margin=0.18,
                net_margin=0.07,
                revenue_cagr_3y=0.24,
                earnings_volatility=0.32,
            ),
            notes="美股整车对照：量、能源和机器人叙事；不要和比亚迪横比 PE。",
        ),
        Stock(
            symbol="GOOGL",
            name="谷歌",
            name_en="Alphabet",
            market=Market.US,
            board="NASDAQ",
            sector="信息技术",
            industry="云计算",
            style=SectorStyle.INTERNET,
            currency="USD",
            price=165.0,
            shares_out=1.22e10,
            pe_ttm=22.0,
            pb=6.4,
            ev_ebitda=14.0,
            fcf_yield=0.032,
            dividend_yield=0.005,
            beta=1.02,
            southbound_eligible=False,
            northbound_eligible=False,
            dual_class=True,
            shenwan_industry="互联网服务",
            gics_industry="Interactive Media & Services",
            financials=_corp(
                revenue=3.5e11,
                net_income=9.4e10,
                roe=0.30,
                roic=0.25,
                gross_margin=0.57,
                net_margin=0.27,
                revenue_cagr_3y=0.11,
            ),
            notes="广告利润池养云和模型；AI 资本开支会压近两年 FCF。",
        ),
        Stock(
            symbol="AMZN",
            name="亚马逊",
            name_en="Amazon",
            market=Market.US,
            board="NASDAQ",
            sector="信息技术",
            industry="云计算",
            style=SectorStyle.INTERNET,
            currency="USD",
            price=185.0,
            shares_out=1.05e10,
            pe_ttm=38.0,
            pb=7.8,
            ev_ebitda=16.0,
            fcf_yield=0.018,
            dividend_yield=0.0,
            beta=1.15,
            southbound_eligible=False,
            northbound_eligible=False,
            dual_class=False,
            shenwan_industry="互联网服务",
            gics_industry="Broadline Retail",
            financials=_corp(
                revenue=6.2e11,
                net_income=4.4e10,
                roe=0.22,
                roic=0.12,
                gross_margin=0.47,
                net_margin=0.07,
                revenue_cagr_3y=0.11,
            ),
            notes="零售薄利、AWS 厚利；云资本开支与广告是近两年主变量。",
        ),
    ]
    return {row.symbol: row for row in rows}


def extra_industries() -> dict[str, IndustrySnapshot]:
    return {
        "创新药": IndustrySnapshot(
            name="创新药",
            name_en="Innovative drugs",
            markets=(Market.A_SHARE, Market.HK, Market.US),
            growth_3y=0.14,
            expected_growth_2y=0.12,
            cr5=0.28,
            hhi=720,
            median_roe=0.08,
            median_roic=0.06,
            policy_score=55,
            disruption_risk=72,
            valuation_percentile=76,
            profit_pool_trend=0.04,
            cycle_position="early",
            leaders=("LLY", "600276.SS", "06160.HK"),
            aliases=("生物药", "Biotech", "制药", "医药"),
            constituents=("600276.SS", "06160.HK", "LLY"),
            notes="利润在临床兑现和支付方，不在故事。中美管线不能用同一 PE。",
        ),
        "保险": IndustrySnapshot(
            name="保险",
            name_en="Insurance",
            markets=(Market.A_SHARE, Market.HK),
            growth_3y=0.05,
            expected_growth_2y=0.06,
            cr5=0.52,
            hhi=1100,
            median_roe=0.13,
            median_roic=0.10,
            policy_score=58,
            disruption_risk=40,
            valuation_percentile=38,
            profit_pool_trend=0.01,
            cycle_position="mid",
            leaders=("601318.SS", "01299.HK"),
            aliases=("寿险", "Insurance", "P&C"),
            constituents=("601318.SS", "02318.HK", "01299.HK"),
            notes="NBV、投资收益率和地产敞口；平安 A/H 与友邦不是同一把尺子。",
        ),
        "光伏": IndustrySnapshot(
            name="光伏",
            name_en="Solar",
            markets=(Market.A_SHARE,),
            growth_3y=0.18,
            expected_growth_2y=0.08,
            cr5=0.48,
            hhi=1050,
            median_roe=0.08,
            median_roic=0.06,
            policy_score=68,
            disruption_risk=65,
            valuation_percentile=32,
            profit_pool_trend=-0.04,
            cycle_position="trough",
            leaders=("601012.SS",),
            aliases=("太阳能", "Solar", "硅料"),
            constituents=("601012.SS",),
            notes="装机可以很好看，硅料和组件价格战会把利润打穿。",
        ),
        "石油": IndustrySnapshot(
            name="石油",
            name_en="Oil & gas",
            markets=(Market.A_SHARE, Market.HK, Market.US),
            growth_3y=0.06,
            expected_growth_2y=0.03,
            cr5=0.58,
            hhi=1400,
            median_roe=0.14,
            median_roic=0.11,
            policy_score=50,
            disruption_risk=45,
            valuation_percentile=42,
            profit_pool_trend=0.00,
            cycle_position="mid",
            leaders=("00883.HK", "XOM"),
            aliases=("油气", "Oil", "能源"),
            constituents=("601857.SS", "00883.HK", "XOM"),
            notes="油价周期 + 分红/回购纪律；三地税费和储量口径不同。",
        ),
        "公用事业": IndustrySnapshot(
            name="公用事业",
            name_en="Utilities",
            markets=(Market.A_SHARE,),
            growth_3y=0.07,
            expected_growth_2y=0.05,
            cr5=0.40,
            hhi=880,
            median_roe=0.14,
            median_roic=0.09,
            policy_score=64,
            disruption_risk=28,
            valuation_percentile=58,
            profit_pool_trend=0.01,
            cycle_position="late",
            leaders=("600900.SS",),
            aliases=("水电", "电力", "Utilities"),
            constituents=("600900.SS",),
            notes="类债券权益；电价与来水，不是科技成长。",
        ),
        "交易所": IndustrySnapshot(
            name="交易所",
            name_en="Exchanges",
            markets=(Market.HK,),
            growth_3y=0.04,
            expected_growth_2y=0.06,
            cr5=0.90,
            hhi=2500,
            median_roe=0.24,
            median_roic=0.20,
            policy_score=60,
            disruption_risk=35,
            valuation_percentile=70,
            profit_pool_trend=0.02,
            cycle_position="mid",
            leaders=("00388.HK",),
            aliases=("港交所", "HKEX", "Exchange"),
            constituents=("00388.HK",),
            notes="垄断收费站：成交、上市、互联互通；IPO 冷暖会改利润弹性。",
        ),
    }


def extra_chains() -> dict[str, ValueChain]:
    return {
        "energy": ValueChain(
            id="energy",
            name="能源对照链",
            name_en="Energy comparison",
            aliases=("能源", "油气", "光伏产业链", "Energy"),
            thesis="化石能源分红和绿电装机不是同一利润池；公用事业吃的是电价合同。",
            notes="对照切片，不是严格上下游。油价、组件价格和来水会改谁留下利润。",
            nodes=(
                ChainNode(role="upstream", industry="石油", captures="储量与油价：现金牛，政策与碳约束是上限。"),
                ChainNode(role="midstream", industry="光伏", captures="制造环节：量的故事，价的战场。", bottleneck=True),
                ChainNode(role="downstream", industry="公用事业", captures="电价与利用率：把一次能源变成可分红的现金流。"),
            ),
        ),
        "health": ValueChain(
            id="health",
            name="创新药对照",
            name_en="Drug pipeline comparison",
            aliases=("医药", "Biotech", "创新药产业链"),
            thesis="礼来的代谢管线和恒瑞/百济的兑现节奏不是同一估值语言。",
            notes="不是原料药到制剂的制造链，是三地创新药利润池对照。",
            nodes=(
                ChainNode(
                    role="upstream",
                    industry="创新药",
                    captures="临床与支付方：真正的瓶颈是适应症和报销，不是工厂。",
                    bottleneck=True,
                ),
            ),
        ),
    }


def patch_industries(industries: dict[str, IndustrySnapshot]) -> None:
    industries["白酒"] = replace(
        industries["白酒"],
        constituents=("600519.SS", "000858.SZ"),
        leaders=("600519.SS", "000858.SZ"),
    )
    industries["新能源车"] = replace(
        industries["新能源车"],
        constituents=("002594.SZ", "01211.HK", "TSLA"),
        leaders=("002594.SZ", "TSLA"),
        markets=(Market.A_SHARE, Market.HK, Market.US),
    )
    industries["云计算"] = replace(
        industries["云计算"],
        constituents=("MSFT", "09988.HK", "GOOGL", "AMZN"),
        leaders=("MSFT", "GOOGL"),
    )
    industries["消费电子"] = replace(
        industries["消费电子"],
        constituents=("AAPL", "01810.HK"),
        leaders=("AAPL",),
        markets=(Market.US, Market.HK),
    )


IPOS: tuple[IPODeal, ...] = (
    IPODeal(
        id="star-compute",
        name="星辰先进",
        name_en="Stellar Compute (sample)",
        market=Market.A_SHARE,
        board="SSE STAR",
        industry="全球半导体",
        status="hearing",
        expected_date="2026-10-18",
        currency="CNY",
        proceeds=4.2e9,
        sponsor="中金公司（样本）",
        notes="科创板人工智能芯片设计上会样本。未上市，不能当已有代码去 Yahoo 打分。",
        comparables=("NVDA", "AVGO", "TSM"),
        chain_id="ai",
    ),
    IPODeal(
        id="chinext-robot",
        name="江淮智造",
        name_en="Jianghuai Robotics (sample)",
        market=Market.A_SHARE,
        board="SZSE ChiNext",
        industry="新能源车",
        status="passed",
        expected_date="2026-09-28",
        currency="CNY",
        proceeds=2.1e9,
        sponsor="中信证券（样本）",
        notes="创业板过会，工业机器人+汽车客户。过会不等于定价合理。",
        comparables=("002594.SZ", "TSLA"),
        chain_id="ev",
    ),
    IPODeal(
        id="star-bio",
        name="海州生物",
        name_en="Haizhou Bio (sample)",
        market=Market.A_SHARE,
        board="SSE STAR",
        industry="创新药",
        status="subscribed",
        expected_date="2026-11-05",
        currency="CNY",
        proceeds=1.6e9,
        sponsor="华泰联合（样本）",
        notes="科创板申购周样本。看现金跑道和适应症，不要看「医药高景气」。",
        comparables=("600276.SS", "06160.HK"),
        chain_id="health",
    ),
    IPODeal(
        id="hk-med",
        name="云帆医药",
        name_en="CloudSail Pharma (sample)",
        market=Market.HK,
        board="HKEX Main",
        industry="创新药",
        status="filed",
        expected_date="2026-10-30",
        currency="HKD",
        proceeds=3.8e9,
        sponsor="高盛 / 中金（样本）",
        notes="港股 18A 风格申报样本。未盈利生物科技，南向不一定可买。",
        comparables=("06160.HK", "LLY"),
        chain_id="health",
    ),
    IPODeal(
        id="hk-consumer",
        name="南岛生活",
        name_en="South Island Lifestyle (sample)",
        market=Market.HK,
        board="HKEX Main",
        industry="本地生活",
        status="priced",
        expected_date="2026-12-08",
        currency="HKD",
        proceeds=2.4e9,
        sponsor="摩根士丹利（样本）",
        notes="已定价待上市样本。本地生活利润仍取决于补贴，不是 AI 故事。",
        comparables=("03690.HK",),
        chain_id="ai",
    ),
    IPODeal(
        id="us-compute",
        name="Helios Compute",
        name_en="Helios Compute (sample)",
        market=Market.US,
        board="NASDAQ",
        industry="云计算",
        status="filed",
        expected_date="2026-09-22",
        currency="USD",
        proceeds=1.1e9,
        sponsor="Goldman Sachs (sample)",
        notes="S-1 申报样本：租 GPU 的云中间层。利润看差价和折旧，不是「AI 必涨」。",
        comparables=("MSFT", "AMZN", "NVDA"),
        chain_id="ai",
    ),
    IPODeal(
        id="us-bio",
        name="Northwind Bio",
        name_en="Northwind Bio (sample)",
        market=Market.US,
        board="NASDAQ",
        industry="创新药",
        status="listed",
        expected_date="2026-08-14",
        currency="USD",
        proceeds=4.2e8,
        sponsor="Morgan Stanley (sample)",
        notes="已上市但未纳入打分宇宙的样本，用来演示「上市 ≠ 进入研究组合」。",
        comparables=("LLY",),
        chain_id="health",
    ),
)


def get_ipo(ipo_id: str) -> IPODeal:
    key = ipo_id.strip().lower()
    for item in IPOS:
        labels = (item.id, item.name, item.name_en.lower())
        if key in {_norm(x) for x in labels} or ipo_id.strip() == item.name:
            return item
    raise KeyError(f"unknown IPO: {ipo_id}")


def _norm(text: str) -> str:
    return text.strip().lower().replace(" ", "").replace("-", "").replace("_", "")
