"""Illustrative multi-market universe. Figures are research fixtures, not live quotes."""

from __future__ import annotations

from quant.models import Financials, IndustrySnapshot, Market, ResearchReport, SectorStyle, Stock


def _f(**kwargs) -> Financials:
    return Financials(**kwargs)


STOCKS: dict[str, Stock] = {
    "600519.SS": Stock(
        symbol="600519.SS",
        name="贵州茅台",
        name_en="Kweichow Moutai",
        market=Market.A_SHARE,
        board="SSE",
        sector="主要消费",
        industry="白酒",
        style=SectorStyle.CONSUMER,
        currency="CNY",
        price=1480.0,
        shares_out=1.256e9,
        pe_ttm=22.5,
        pb=8.4,
        ev_ebitda=16.0,
        fcf_yield=0.041,
        dividend_yield=0.018,
        beta=0.72,
        southbound_eligible=False,
        northbound_eligible=True,
        dual_class=False,
        shenwan_industry="白酒",
        gics_industry="Distillers & Vintners",
        financials=_f(
            revenue=1.74e11,
            net_income=8.6e10,
            operating_cash_flow=8.1e10,
            free_cash_flow=7.6e10,
            total_equity=2.2e11,
            total_debt=5e9,
            cash=1.5e11,
            ebit=1.15e11,
            ebitda=1.18e11,
            interest_expense=2e8,
            current_assets=2.1e11,
            current_liabilities=4.5e10,
            revenue_cagr_3y=0.16,
            eps_cagr_3y=0.15,
            roe=0.31,
            roic=0.29,
            gross_margin=0.92,
            net_margin=0.49,
            earnings_volatility=0.08,
            receivable_days=2,
            inventory_days=1100,
        ),
        notes="北向核心持仓；品牌护城河极强，估值贵是常态。",
    ),
    "300750.SZ": Stock(
        symbol="300750.SZ",
        name="宁德时代",
        name_en="CATL",
        market=Market.A_SHARE,
        board="SZSE",
        sector="制造",
        industry="电池",
        style=SectorStyle.INDUSTRIAL,
        currency="CNY",
        price=210.0,
        shares_out=4.4e9,
        pe_ttm=19.8,
        pb=4.1,
        ev_ebitda=12.5,
        fcf_yield=0.028,
        dividend_yield=0.012,
        beta=1.25,
        southbound_eligible=False,
        northbound_eligible=True,
        dual_class=False,
        shenwan_industry="电池",
        gics_industry="Electrical Equipment",
        ah_pair_symbol="3750.HK",
        financials=_f(
            revenue=3.6e11,
            net_income=4.9e10,
            operating_cash_flow=7.2e10,
            free_cash_flow=2.6e10,
            total_equity=2.3e11,
            total_debt=1.1e11,
            cash=1.6e11,
            ebit=6.1e10,
            ebitda=8.8e10,
            interest_expense=3.2e9,
            current_assets=4.2e11,
            current_liabilities=2.4e11,
            revenue_cagr_3y=0.21,
            eps_cagr_3y=0.12,
            roe=0.22,
            roic=0.14,
            gross_margin=0.24,
            net_margin=0.136,
            earnings_volatility=0.22,
            receivable_days=70,
            inventory_days=85,
        ),
        notes="锂电周期+全球份额；A/H 价差是港股通研究的经典样本。",
    ),
    "3750.HK": Stock(
        symbol="3750.HK",
        name="宁德时代-H",
        name_en="CATL-H",
        market=Market.HK,
        board="HKEX",
        sector="制造",
        industry="电池",
        style=SectorStyle.INDUSTRIAL,
        currency="HKD",
        price=194.0,
        shares_out=4.4e8,
        pe_ttm=16.2,
        pb=3.3,
        ev_ebitda=10.4,
        fcf_yield=0.034,
        dividend_yield=0.014,
        beta=1.28,
        southbound_eligible=True,
        northbound_eligible=False,
        dual_class=False,
        shenwan_industry="电池",
        gics_industry="Electrical Equipment",
        ah_pair_symbol="300750.SZ",
        financials=_f(
            revenue=3.6e11,
            net_income=4.9e10,
            operating_cash_flow=7.2e10,
            free_cash_flow=2.6e10,
            total_equity=2.3e11,
            total_debt=1.1e11,
            cash=1.6e11,
            ebit=6.1e10,
            ebitda=8.8e10,
            interest_expense=3.2e9,
            current_assets=4.2e11,
            current_liabilities=2.4e11,
            revenue_cagr_3y=0.21,
            eps_cagr_3y=0.12,
            roe=0.22,
            roic=0.14,
            gross_margin=0.24,
            net_margin=0.136,
            earnings_volatility=0.22,
            receivable_days=70,
            inventory_days=85,
        ),
        notes="H 股样本价用于演示 A/H 溢价，不是实时盘口。",
    ),
    "600036.SS": Stock(
        symbol="600036.SS",
        name="招商银行",
        name_en="China Merchants Bank",
        market=Market.A_SHARE,
        board="SSE",
        sector="金融",
        industry="银行",
        style=SectorStyle.FINANCIAL,
        currency="CNY",
        price=36.5,
        shares_out=2.52e10,
        pe_ttm=6.4,
        pb=0.92,
        ev_ebitda=None,
        fcf_yield=None,
        dividend_yield=0.051,
        beta=0.88,
        southbound_eligible=False,
        northbound_eligible=True,
        dual_class=False,
        ah_pair_symbol="3968.HK",
        shenwan_industry="银行",
        gics_industry="Diversified Banks",
        financials=_f(
            revenue=3.3e11,
            net_income=1.46e11,
            operating_cash_flow=1.7e11,
            free_cash_flow=1.7e11,
            total_equity=1.05e12,
            total_debt=0.0,
            cash=0.0,
            ebit=1.46e11,
            ebitda=1.46e11,
            interest_expense=1.0,
            current_assets=1.0,
            current_liabilities=1.0,
            revenue_cagr_3y=0.04,
            eps_cagr_3y=0.05,
            roe=0.145,
            roic=0.12,
            gross_margin=0.0,
            net_margin=0.44,
            earnings_volatility=0.07,
            npl_ratio=0.0095,
            core_tier1=0.135,
        ),
        notes="零售银行质量标杆；A/H 长期溢价，适合讲折溢价而不是无风险套利。",
    ),
    "3968.HK": Stock(
        symbol="3968.HK",
        name="招商银行-H",
        name_en="CMB-H",
        market=Market.HK,
        board="HKEX",
        sector="金融",
        industry="银行",
        style=SectorStyle.FINANCIAL,
        currency="HKD",
        price=28.5,
        shares_out=4.59e9,
        pe_ttm=5.2,
        pb=0.74,
        ev_ebitda=None,
        fcf_yield=None,
        dividend_yield=0.062,
        beta=0.95,
        southbound_eligible=True,
        northbound_eligible=False,
        dual_class=False,
        ah_pair_symbol="600036.SS",
        shenwan_industry="银行",
        gics_industry="Diversified Banks",
        financials=_f(
            revenue=3.3e11,
            net_income=1.46e11,
            operating_cash_flow=1.7e11,
            free_cash_flow=1.7e11,
            total_equity=1.05e12,
            total_debt=0.0,
            cash=0.0,
            ebit=1.46e11,
            ebitda=1.46e11,
            interest_expense=1.0,
            current_assets=1.0,
            current_liabilities=1.0,
            revenue_cagr_3y=0.04,
            eps_cagr_3y=0.05,
            roe=0.145,
            roic=0.12,
            gross_margin=0.0,
            net_margin=0.44,
            earnings_volatility=0.07,
            npl_ratio=0.0095,
            core_tier1=0.135,
        ),
        notes="港股通南向重仓品种之一，股息和折价是常见叙事。",
    ),
    "00700.HK": Stock(
        symbol="00700.HK",
        name="腾讯控股",
        name_en="Tencent",
        market=Market.HK,
        board="HKEX",
        sector="可选消费/科技",
        industry="互联网平台",
        style=SectorStyle.INTERNET,
        currency="HKD",
        price=410.0,
        shares_out=9.3e9,
        pe_ttm=19.5,
        pb=3.6,
        ev_ebitda=13.2,
        fcf_yield=0.046,
        dividend_yield=0.011,
        beta=1.15,
        southbound_eligible=True,
        northbound_eligible=False,
        dual_class=True,
        gics_industry="Interactive Media & Services",
        financials=_f(
            revenue=6.6e11,
            net_income=1.9e11,
            operating_cash_flow=2.4e11,
            free_cash_flow=1.75e11,
            total_equity=9.5e11,
            total_debt=3.6e11,
            cash=4.1e11,
            ebit=1.85e11,
            ebitda=2.3e11,
            interest_expense=1.1e10,
            current_assets=5.2e11,
            current_liabilities=3.1e11,
            revenue_cagr_3y=0.09,
            eps_cagr_3y=0.11,
            roe=0.20,
            roic=0.13,
            gross_margin=0.51,
            net_margin=0.29,
            earnings_volatility=0.18,
            shares_dilution_3y=0.01,
            receivable_days=35,
        ),
        notes="港股通核心资产；游戏+广告+金融科技，监管与竞争是主风险。",
    ),
    "03690.HK": Stock(
        symbol="03690.HK",
        name="美团",
        name_en="Meituan",
        market=Market.HK,
        board="HKEX",
        sector="可选消费",
        industry="本地生活",
        style=SectorStyle.INTERNET,
        currency="HKD",
        price=125.0,
        shares_out=6.2e9,
        pe_ttm=24.0,
        pb=3.9,
        ev_ebitda=16.5,
        fcf_yield=0.032,
        dividend_yield=0.0,
        beta=1.42,
        southbound_eligible=True,
        northbound_eligible=False,
        dual_class=True,
        gics_industry="Internet & Direct Marketing Retail",
        financials=_f(
            revenue=3.3e11,
            net_income=2.7e10,
            operating_cash_flow=4.8e10,
            free_cash_flow=3.9e10,
            total_equity=1.7e11,
            total_debt=5.5e10,
            cash=1.4e11,
            ebit=3.4e10,
            ebitda=4.6e10,
            interest_expense=2.1e9,
            current_assets=1.9e11,
            current_liabilities=9.5e10,
            revenue_cagr_3y=0.18,
            eps_cagr_3y=0.25,
            roe=0.16,
            roic=0.11,
            gross_margin=0.35,
            net_margin=0.082,
            earnings_volatility=0.35,
            shares_dilution_3y=0.03,
            receivable_days=18,
        ),
        notes="本地生活竞争激烈，利润率对补贴和监管敏感。",
    ),
    "AAPL": Stock(
        symbol="AAPL",
        name="苹果",
        name_en="Apple",
        market=Market.US,
        board="NASDAQ",
        sector="信息技术",
        industry="消费电子",
        style=SectorStyle.TECH_HARDWARE,
        currency="USD",
        price=225.0,
        shares_out=1.52e10,
        pe_ttm=33.0,
        pb=48.0,
        ev_ebitda=24.0,
        fcf_yield=0.031,
        dividend_yield=0.0045,
        beta=1.18,
        southbound_eligible=False,
        northbound_eligible=False,
        dual_class=False,
        gics_industry="Technology Hardware",
        financials=_f(
            revenue=3.91e11,
            net_income=9.4e10,
            operating_cash_flow=1.18e11,
            free_cash_flow=1.08e11,
            total_equity=5.7e10,
            total_debt=1.06e11,
            cash=6.2e10,
            ebit=1.23e11,
            ebitda=1.34e11,
            interest_expense=3.9e9,
            current_assets=1.43e11,
            current_liabilities=1.65e11,
            revenue_cagr_3y=0.02,
            eps_cagr_3y=0.07,
            roe=1.45,
            roic=0.48,
            gross_margin=0.46,
            net_margin=0.24,
            earnings_volatility=0.11,
            shares_dilution_3y=-0.08,
            receivable_days=28,
            inventory_days=12,
        ),
        notes="美股质量+回购机器；PE 贵但 FCF 和资本回报极强。",
    ),
    "NVDA": Stock(
        symbol="NVDA",
        name="英伟达",
        name_en="NVIDIA",
        market=Market.US,
        board="NASDAQ",
        sector="信息技术",
        industry="半导体",
        style=SectorStyle.TECH_HARDWARE,
        currency="USD",
        price=120.0,
        shares_out=2.45e10,
        pe_ttm=42.0,
        pb=32.0,
        ev_ebitda=34.0,
        fcf_yield=0.019,
        dividend_yield=0.0003,
        beta=1.72,
        southbound_eligible=False,
        northbound_eligible=False,
        dual_class=False,
        gics_industry="Semiconductors",
        financials=_f(
            revenue=1.13e11,
            net_income=5.9e10,
            operating_cash_flow=6.4e10,
            free_cash_flow=5.7e10,
            total_equity=7.9e10,
            total_debt=1.0e10,
            cash=3.5e10,
            ebit=6.8e10,
            ebitda=7.1e10,
            interest_expense=2.6e8,
            current_assets=7.4e10,
            current_liabilities=1.8e10,
            revenue_cagr_3y=0.72,
            eps_cagr_3y=0.95,
            roe=0.91,
            roic=0.75,
            gross_margin=0.73,
            net_margin=0.52,
            earnings_volatility=0.40,
            receivable_days=45,
            inventory_days=110,
        ),
        notes="算力周期龙头；高增长对高估值，颠覆风险来自客户自制与资本开支回落。",
    ),
    "JPM": Stock(
        symbol="JPM",
        name="摩根大通",
        name_en="JPMorgan Chase",
        market=Market.US,
        board="NYSE",
        sector="金融",
        industry="银行",
        style=SectorStyle.FINANCIAL,
        currency="USD",
        price=210.0,
        shares_out=2.84e9,
        pe_ttm=12.2,
        pb=1.85,
        ev_ebitda=None,
        fcf_yield=None,
        dividend_yield=0.023,
        beta=1.08,
        southbound_eligible=False,
        northbound_eligible=False,
        dual_class=False,
        gics_industry="Diversified Banks",
        financials=_f(
            revenue=1.78e11,
            net_income=5.4e10,
            operating_cash_flow=6.1e10,
            free_cash_flow=6.1e10,
            total_equity=3.4e11,
            total_debt=0.0,
            cash=0.0,
            ebit=5.4e10,
            ebitda=5.4e10,
            interest_expense=1.0,
            current_assets=1.0,
            current_liabilities=1.0,
            revenue_cagr_3y=0.11,
            eps_cagr_3y=0.09,
            roe=0.16,
            roic=0.14,
            gross_margin=0.0,
            net_margin=0.30,
            earnings_volatility=0.16,
            npl_ratio=0.007,
            core_tier1=0.151,
        ),
        notes="美股银行对照样本：同样银行，美股 PB 体系与 A/H 完全不同。",
    ),
}


INDUSTRIES: dict[str, IndustrySnapshot] = {
    "白酒": IndustrySnapshot(
        name="白酒",
        name_en="Baijiu",
        markets=(Market.A_SHARE,),
        growth_3y=0.08,
        expected_growth_2y=0.05,
        cr5=0.62,
        hhi=1450,
        median_roe=0.22,
        median_roic=0.20,
        policy_score=58,
        disruption_risk=25,
        valuation_percentile=62,
        profit_pool_trend=0.01,
        cycle_position="mid",
        leaders=("600519.SS",),
        notes="高端宴席与礼品需求稳，大众价格带竞争更卷；几乎是纯 A 股行业。",
    ),
    "动力电池": IndustrySnapshot(
        name="动力电池",
        name_en="EV Battery",
        markets=(Market.A_SHARE, Market.HK),
        growth_3y=0.24,
        expected_growth_2y=0.12,
        cr5=0.71,
        hhi=1800,
        median_roe=0.14,
        median_roic=0.10,
        policy_score=72,
        disruption_risk=55,
        valuation_percentile=48,
        profit_pool_trend=-0.02,
        cycle_position="mid",
        leaders=("300750.SZ", "3750.HK"),
        notes="全球份额向龙头集中，但资本开支与价格战会吃掉利润池。",
    ),
    "中资银行": IndustrySnapshot(
        name="中资银行",
        name_en="Chinese Banks",
        markets=(Market.A_SHARE, Market.HK),
        growth_3y=0.03,
        expected_growth_2y=0.03,
        cr5=0.48,
        hhi=900,
        median_roe=0.10,
        median_roic=0.09,
        policy_score=52,
        disruption_risk=35,
        valuation_percentile=22,
        profit_pool_trend=-0.01,
        cycle_position="trough",
        leaders=("600036.SS", "3968.HK"),
        notes="资产质量与净息差是主线；A 股溢价、H 股折价长期存在。",
    ),
    "互联网平台": IndustrySnapshot(
        name="互联网平台",
        name_en="China Internet",
        markets=(Market.HK, Market.US),
        growth_3y=0.07,
        expected_growth_2y=0.08,
        cr5=0.68,
        hhi=1600,
        median_roe=0.13,
        median_roic=0.10,
        policy_score=48,
        disruption_risk=60,
        valuation_percentile=40,
        profit_pool_trend=0.03,
        cycle_position="early",
        leaders=("00700.HK", "03690.HK"),
        notes="监管从收缩走向常态化，但竞争与广告预算仍决定利润弹性。",
    ),
    "全球半导体": IndustrySnapshot(
        name="全球半导体",
        name_en="Global Semiconductors",
        markets=(Market.US, Market.HK, Market.A_SHARE),
        growth_3y=0.18,
        expected_growth_2y=0.14,
        cr5=0.55,
        hhi=1300,
        median_roe=0.18,
        median_roic=0.16,
        policy_score=44,
        disruption_risk=70,
        valuation_percentile=78,
        profit_pool_trend=0.08,
        cycle_position="mid",
        leaders=("NVDA",),
        notes="AI 资本开支驱动；出口管制与客户自制是美股/A 股共同变量。",
    ),
}


REPORTS: dict[str, ResearchReport] = {
    "tencent-init": ResearchReport(
        title="腾讯：游戏与广告修复，首次覆盖买入",
        broker="某券商海外",
        language="zh",
        symbol="00700.HK",
        rating="buy",
        target_price=620.0,
        current_price=410.0,
        published="2026-03-01",
        has_initiation=True,
        broker_is_underwriter=False,
        has_quant_model=False,
        body=(
            "核心结论：我们认为腾讯将重新获得游戏与广告的利润弹性。"
            "投资逻辑是国内游戏版号常态化，广告主预算回升，以及金融科技合规后利润率修复。"
            "关键假设包括：明年游戏收入增长 12%，广告 ASP 提升 6%，市占维持。"
            "目标价 620 港元，对应 28x PE，未做完整敏感性分析。"
            "风险：宏观经济波动，监管再收紧，竞争加剧。"
            "渠道调研显示部分广告主预算回升，但样本有限。"
        ),
    ),
    "cmb-ah": ResearchReport(
        title="招商银行 A/H：质量溢价仍在，H 股股息更有吸引力",
        broker="中资研究所",
        language="zh",
        symbol="3968.HK",
        rating="overweight",
        target_price=46.0,
        current_price=28.5,
        published="2026-02-12",
        has_quant_model=True,
        body=(
            "核心结论：招行零售资产质量仍优于同业，H 股 PB 0.74x 低于 A 股。"
            "投资逻辑：净息差企稳、财富管理中收回升、港股通南向持续增持。"
            "关键假设：NPL 维持 1% 以下，ROE 14%-15%，派息率 35%。"
            "估值采用 PB-ROE 与 DDM，并对净息差做了敏感性。"
            "风险：房地产相关敞口恶化、零售信贷成本上升、若内地资金流出则折价扩大。"
            "公告显示核心一级资本充足率 13.5%。"
        ),
    ),
    "nvda-hype": ResearchReport(
        title="NVIDIA: only way is up",
        broker="Promo Capital",
        language="en",
        symbol="NVDA",
        rating="buy",
        target_price=260.0,
        current_price=120.0,
        published="2026-01-08",
        has_initiation=True,
        broker_is_underwriter=True,
        body=(
            "We believe NVIDIA will keep winning forever. Space is huge and certain. "
            "No real bear case. Must go up. Target implies 2x from here. "
            "Macro risk only. We are also the underwriter on a related financing."
        ),
    ),
}


CONNECT_FLOWS = {
    "00700.HK": {"southbound_holding_change_20d": 0.018, "southbound_rank": 1},
    "03690.HK": {"southbound_holding_change_20d": -0.006, "southbound_rank": 8},
    "3968.HK": {"southbound_holding_change_20d": 0.011, "southbound_rank": 5},
    "3750.HK": {"southbound_holding_change_20d": 0.004, "southbound_rank": 16},
    "600519.SS": {"northbound_holding_change_20d": 0.007, "northbound_rank": 3},
    "300750.SZ": {"northbound_holding_change_20d": -0.009, "northbound_rank": 11},
    "600036.SS": {"northbound_holding_change_20d": 0.003, "northbound_rank": 9},
}


def universe() -> list[Stock]:
    return list(STOCKS.values())


def get_stock(symbol: str) -> Stock:
    key = symbol.strip()
    if key in STOCKS:
        return STOCKS[key]
    upper = {k.upper(): k for k in STOCKS}
    if key.upper() in upper:
        return STOCKS[upper[key.upper()]]
    raise KeyError(f"unknown sample symbol: {symbol}")


def industries() -> list[IndustrySnapshot]:
    return list(INDUSTRIES.values())


def get_industry(name: str) -> IndustrySnapshot:
    if name in INDUSTRIES:
        return INDUSTRIES[name]
    for item in INDUSTRIES.values():
        if item.name_en.lower() == name.lower() or item.name == name:
            return item
    raise KeyError(f"unknown industry: {name}")
